import Footer from '@/components/common/Footer'
import Nav from '@/components/common/Nav'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Marechal Web - login',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <header>
        <Nav />
      </header>
      <main className="flex flex-col items-center border-spacing-1">
        {children}
      </main>
      <Footer />
    </>
  )
}
